### ISSUE TITLE
giblib: checksum mismatch

### ISSUE THREAD

**Issue by trbednarzyk** [kisslinux/community#712]
The source URL is fine now and all that needs to be run is `kiss c giblib`. Running it on my machine gave me the following for the checksums file:
`176611c4d88d742ea4013991ad54c2f9d2feefbc97a28434c0f48922ebaa8bac  giblib-1.2.4.tar.gz`

@aicsx

**Comment by aicsx** [comment]
uhm ...what is the issue? 76611c4d88d742ea4013991ad54c2f9d2feefbc97a28434c0f48922ebaa8bac  giblib-1.2.4.tar.gz

it's exactly what it has to return.

**Comment by trbednarzyk** [comment]
I did clear the cache beforehand to be sure that I was using the same source as the package.
However, I still got a checksum mismatch. The checksum you typed above appears to be missing the first character (1), but that's not what you put in the package at all regardless:
```
~ $ cat /var/db/community/community/giblib/sources
https://github.com/aicsx/kiss-repo/raw/master/giblib/giblib-1.2.4.tar.gz
~ $ cat /var/db/community/community/giblib/checksums
cce34a7173fdda59c88d2a7d59035bc7f694bef78a8001b36b10382a053a95b3  giblib-1.2.4.tar.gz
```
As you can see, I'm up to date with the repo as the sources file matches what you changed it to in the last PR, but the checksums you put in is not what it should be.

**Comment by aicsx** [comment]
I just wrong to paste missing 1 * but there is.
The source is exactly the same, it is the source that changes and therefore it is normal for the check to be different from a different source. The checksums you refer to is before the source change. Update the repo, clear cache and build you shouldn't have any problems. I have tried and I have no errors.

**Comment by trbednarzyk** [comment]
Again, I was already up to date:
```
-> /var/db/community
-> /var/db/community Need root to update
Already up to date.
```
If you look at the link you sent, you will find that the checksums file in the PR is not the checksums you pasted in the first reply.

**Comment by trbednarzyk** [comment]
Actually looking at it again, you had the correct checksum and replaced it with an incorrect one.

**Comment by aicsx** [comment]
wait wait, you're right! 
~/kiss-repo/giblib $ sha256sum giblib-1.2.4.tar.gz
176611c4d88d742ea4013991ad54c2f9d2feefbc97a28434c0f48922ebaa8bac  giblib-1.2.4.tar.gz

 probably the build from new source generated a different checksum and it upload in repo -.-'  it was probably a "kiss c" error ... i am checking to upgrade. I have to investigate with dylan to understand why this happened. PR with fix will be active in the next few minutes. Thanks for the feedback.

**Comment by dylanaraps** [comment]
I'm still getting a checksum mismatch with your PR merged. Would you like me to update the checksums and push to GitHub? (All that's needed is `kiss c giblib`.

**Comment by trbednarzyk** [comment]
Yeah, I'm also getting the same issue. I just updated and I see the exact same checksum as before:
```
~ $ kiss u
-> Updating repositories
-> /home/kuro-kun/kiss_repo/Personal-KISS-Repo
Already up to date.
-> /var/db/kiss/repo [signed ✓]
-> /var/db/kiss/repo Need root to update
Already up to date.
-> /var/db/community
-> /var/db/community Need root to update
Already up to date.
-> Checking for new package versions
-> Everything is up to date
~ $ cat /var/db/community/community/giblib/checksums
cce34a7173fdda59c88d2a7d59035bc7f694bef78a8001b36b10382a053a95b3  giblib-1.2.4.tar.gz
```

**Comment by dylanaraps** [comment]
Any update on this? (Have we resolved this?)

**Comment by aicsx** [comment]
$ sha256sum giblib-1.2.4.tar.gz 
176611c4d88d742ea4013991ad54c2f9d2feefbc97a28434c0f48922ebaa8bac  giblib-1.2.4.tar.gz

I repeat that kiss c has created an incorrect checksums and I have not yet understood why .. when I made s/blob/raw on source but I have already committed you with the correct change. 
Address for sources change but bot chrcksum. 
please https://github.com/kisslinux/community/commit/290df0065a6c9992eb32bac98a8d75fff06a5142 . merge It.

**Comment by dylanaraps** [comment]
I'm still getting a mismatch. These are the correct checksums according to kiss:

```
176611c4d88d742ea4013991ad54c2f9d2feefbc97a28434c0f48922ebaa8bac  giblib-1.2.4.tar.gz
```

I went ahead and pushed these to the package. An issue like this shouldn't stay open this long.
